Get data in webconsole by Ipdiscover scan from the server
OCSInventory-NG/OCSInventory-ocsreports pull request #1209
Opened 2021-06-21 13:57 UTC by Djily90

### Status
**READY/IN DEVELOPMENT/HOLD** (remove the irrevelant words)

### Description
The issu to fix here is the ipdiscover scan from server doesn't return anythings in the webconsole. For that we just add an option when the ipdiscover is matching with a TAG and return it in the webconsole.

### Documentation
In the case, your pull request need the documentation to be modified, please say it here.
You can also directly create a pull request for the documentation here : https://github.com/OCSInventory-NG/Wiki

Note : Merge process will be faster if the documentation is already written

2021-06-21 14:03 UTC, Djily90 commented
To start an ipdiscover scan from server, we must add a tag option if the ipdiscover is joining in a Tag

2021-06-22 15:58 UTC, RudyLaurent requested changes

2021-06-22 15:58 UTC, RudyLaurent commented on ipdiscover-util.pl
> +my $tag
Missing `;`

2021-06-22 15:58 UTC, RudyLaurent commented on ipdiscover-util.pl
> +    $tag = $1;
Stop script if -network is present and not -tag or add check before insert

2021-06-22 15:58 UTC, RudyLaurent commented on ipdiscover-util.pl
>  Usage :
Add -tag informations in Usage.

2021-06-24 12:48 UTC, RudyLaurent requested changes

2021-06-24 12:48 UTC, RudyLaurent commented on ipdiscover-util.pl
> +          $dbh->do('INSERT IGNORE INTO netmap(IP,MAC,MASK,NETID,NAME,TAG) VALUES(?s,?,?,?,?)', {}, $ip, $macAddr, $mask, $subnet, $name, $tag);
Error : there are a 's' in query.

2021-06-24 12:48 UTC, RudyLaurent commented on ipdiscover-util.pl
> +        if ($name AND $tag){
Error with 'AND'. Use 'and' or '&&'

2021-06-24 12:48 UTC, RudyLaurent commented on ipdiscover-util.pl
>      } elsif ($scantype eq "ping") { #scan with fping
Set same change for ping.

2021-06-28 15:22 UTC, Djily90 commented on ipdiscover-util.pl
> +          $dbh->do('INSERT IGNORE INTO netmap(IP,MAC,MASK,NETID,NAME,TAG) VALUES(?s,?,?,?,?)', {}, $ip, $macAddr, $mask, $subnet, $name, $tag);
I fix it

2021-06-29 09:36 UTC, Djily90 commented on ipdiscover-util.pl
>      } elsif ($scantype eq "ping") { #scan with fping
All fix are done.

2021-07-07 08:17 UTC, Djily90 commented on ipdiscover-util.pl
> +        if ($name AND $tag){
Done !

2021-07-07 08:18 UTC, Djily90 commented on ipdiscover-util.pl
>  Usage :
Done !

2021-07-07 08:18 UTC, Djily90 commented on ipdiscover-util.pl
> +    $tag = $1;
Done !

2021-07-07 08:19 UTC, Djily90 commented on ipdiscover-util.pl
> +my $tag
Done !

2021-07-08 07:24 UTC, Djily90 reviewed
All comments are fixed

2021-07-09 08:09 UTC, merged